// swift-tools-version: 6.0
// Generated by ios-app-manager macos-app.
import PackageDescription
let package = Package(
    name: "RunnerControlCore",
    platforms: [.macOS("14.0")],
    products: [.library(name: "RunnerControlCore", targets: ["RunnerControlCore"])],
    dependencies: [
        .package(url: "https://github.com/relux-works/swift-relux.git", exact: "9.2.0"),
    ],
    targets: [
        .target(name: "RunnerControlCore", dependencies: [
                .product(name: "Relux", package: "swift-relux"),
        ], path: "Sources"),
        .testTarget(name: "RunnerControlCoreTests", dependencies: ["RunnerControlCore"], path: "Tests"),
    ]
)
