// Generated by ios-app-manager macos-app.
import ProjectDescription
let project = Project(
    name: "RunnerControl",
    organizationName: "Relux Works",
    packages: [
        .remote(url: "https://github.com/relux-works/swift-relux.git", requirement: .exact("9.2.0")),
        .remote(url: "https://github.com/sparkle-project/Sparkle", requirement: .exact("2.10.0")),
    ],
    settings: .settings(base: [
        "DEVELOPMENT_TEAM": "262RZ595FP",
        "CODE_SIGN_STYLE": "Automatic",
        "CODE_SIGN_IDENTITY": "Apple Development",
        "SWIFT_VERSION": "6.0",
        "SWIFT_STRICT_CONCURRENCY": "complete",
        "MACOSX_DEPLOYMENT_TARGET": "14.0",
        "ENABLE_HARDENED_RUNTIME": "YES",
    ]),
    targets: [
        .target(
            name: "RunnerControl", destinations: [.mac], product: .app,
            bundleId: "works.relux.runnercontrol", deploymentTargets: .macOS("14.0"),
            infoPlist: .extendingDefault(with: [
                "LSUIElement": .boolean(true),
                "CFBundleShortVersionString": .string("1.1.1"),
                "CFBundleVersion": .string("101.99"),
                "NSHumanReadableCopyright": .string("Relux Works"),
                "SUAutomaticallyUpdate": .boolean(true),
                "SUEnableAutomaticChecks": .boolean(true),
                "SUFeedURL": .string("https://github.com/relux-works/runner-control/releases/latest/download/appcast.xml"),
                "SUPublicEDKey": .string("39zxlS5xFUIf4aqaPWBf2oIi1VBkQ/TdPYLifXzWnS8="),
                "SUVerifyUpdateBeforeExtraction": .boolean(true),
            ]),
            sources: ["Targets/RunnerControl/Sources/**"],
            resources: .resources([.glob(pattern: "Targets/RunnerControl/Resources/**", excluding: [])]),
            dependencies: [.target(name: "RunnerControlCore"), .package(product: "Sparkle")],
            settings: .settings(base: ["ENABLE_APP_SANDBOX": "NO", "CODE_SIGN_IDENTITY": "Apple Development"])
        ),
        .target(
            name: "RunnerControlCore", destinations: [.mac], product: .framework,
            bundleId: "works.relux.runnercontrol.core", deploymentTargets: .macOS("14.0"),
            infoPlist: .default,
            sources: ["Packages/RunnerControlCore/Sources/**"],
            dependencies: [
                .package(product: "Relux"),
            ],
            settings: .settings(base: ["CODE_SIGN_IDENTITY": "Apple Development"])
        ),
        .target(
            name: "RunnerControlCoreTests", destinations: [.mac], product: .unitTests,
            bundleId: "works.relux.runnercontrol.coretests", deploymentTargets: .macOS("14.0"),
            infoPlist: .default,
            sources: ["Packages/RunnerControlCore/Tests/**"],
            dependencies: [.target(name: "RunnerControlCore")],
            settings: .settings(base: ["CODE_SIGN_IDENTITY": "Apple Development"])
        ),
    ]
)
