// Generated by ios-app-manager macos-app.
import ProjectDescription
let project = Project(
    name: "RunnerControl",
    organizationName: "Relux Works",
    packages: [
        .remote(url: "https://github.com/relux-works/swift-relux.git", requirement: .exact("9.2.0")),
    ],
    settings: .settings(base: [
        "DEVELOPMENT_TEAM": "262RZ595FP",
        "CODE_SIGN_STYLE": "Automatic",
        "CODE_SIGN_IDENTITY": "Apple Development",
        "SWIFT_VERSION": "6.0",
        "SWIFT_STRICT_CONCURRENCY": "complete",
        "MACOSX_DEPLOYMENT_TARGET": "14.0",
    ]),
    targets: [
        .target(
            name: "RunnerControl", destinations: [.mac], product: .app,
            bundleId: "works.relux.runnercontrol", deploymentTargets: .macOS("14.0"),
            infoPlist: .extendingDefault(with: [
                "LSUIElement": .boolean(true),
                "CFBundleShortVersionString": .string("1.0.0"),
                "CFBundleVersion": .string("1"),
                "NSHumanReadableCopyright": .string("Relux Works"),
            ]),
            sources: ["Targets/RunnerControl/Sources/**"],
            resources: .resources([.glob(pattern: "Targets/RunnerControl/Resources/**", excluding: [])]),
            dependencies: [.target(name: "RunnerControlCore")],
            settings: .settings(base: ["ENABLE_APP_SANDBOX": "NO", "CODE_SIGN_IDENTITY": "Apple Development"])
        ),
        .target(
            name: "RunnerControlCore", destinations: [.mac], product: .framework,
            bundleId: "works.relux.runnercontrol.core", deploymentTargets: .macOS("14.0"),
            infoPlist: .default,
            sources: ["Packages/RunnerControlCore/Sources/**"],
            dependencies: [
                .package(product: "Relux"),
            ],
            settings: .settings(base: ["CODE_SIGN_IDENTITY": "Apple Development"])
        ),
        .target(
            name: "RunnerControlCoreTests", destinations: [.mac], product: .unitTests,
            bundleId: "works.relux.runnercontrol.coretests", deploymentTargets: .macOS("14.0"),
            infoPlist: .default,
            sources: ["Packages/RunnerControlCore/Tests/**"],
            dependencies: [.target(name: "RunnerControlCore")],
            settings: .settings(base: ["CODE_SIGN_IDENTITY": "Apple Development"])
        ),
    ]
)
