// swift-tools-version: 6.0
// Hand-owned CLI package. Unlike RunnerControlCore (generated by
// ios-app-manager), this package is maintained by hand: the Tuist/Xcode
// scaffold never touches it, and release.sh builds it with `swift build`.
import PackageDescription

let package = Package(
    name: "RunnerControlCLI",
    platforms: [.macOS(.v14)],
    products: [.executable(name: "runner-control", targets: ["RunnerControlCLI"])],
    dependencies: [
        .package(path: "../RunnerControlCore"),
        .package(url: "https://github.com/apple/swift-argument-parser.git", exact: "1.5.0"),
    ],
    targets: [
        .executableTarget(
            name: "RunnerControlCLI",
            dependencies: [
                "RunnerControlCore",
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
            ],
            path: "Sources"
        ),
        .testTarget(
            name: "RunnerControlCLITests",
            dependencies: [
                "RunnerControlCLI",
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
            ],
            path: "Tests"
        ),
    ]
)
