"""Pin CLI/GUI shared constants against the scaffold config.

The CLI companion duplicates a few public values (GitHub App client_id, team
ID, feed URL) and the keychain group suffix; these tests fail the build when
either side drifts instead of shipping a silently split-brain release.
"""
import json
import re
import unittest
from pathlib import Path

REPO = Path(__file__).parents[2]
CONFIG = json.loads((REPO / "ios-app-manager.json").read_text())
CLI_SOURCES = REPO / "Packages" / "RunnerControlCLI" / "Sources"
CORE_SOURCES = REPO / "Packages" / "RunnerControlCore" / "Sources"


def swift_string(path, name):
    text = path.read_text()
    match = re.search(r'(?:static\s+)?(?:public\s+)?(?:let|var)\s+' + re.escape(name) + r'\s*=\s*"([^"]+)"', text)
    assert match, f"{name} not found in {path.name}"
    return match.group(1)


class CLIParity(unittest.TestCase):
    def test_client_id_matches_scaffold(self):
        expected = CONFIG["macos"]["info_plist"]["GitHubAppClientID"]
        found = swift_string(CLI_SOURCES / "CLIConfig.swift", "embeddedClientID")
        self.assertEqual(found, expected)

    def test_feed_url_matches_scaffold(self):
        expected = CONFIG["macos"]["info_plist"]["SUFeedURL"]
        text = (CLI_SOURCES / "AppCommands.swift").read_text()
        self.assertIn(f'"{expected}"', text)

    def test_command_name_matches_product(self):
        package = (REPO / "Packages" / "RunnerControlCLI" / "Package.swift").read_text()
        name = swift_string(CORE_SOURCES / "CLIInstallerService.swift", "commandName")
        self.assertIn(f'executable(name: "{name}"', package)

    def test_helpers_subpath_matches_scripts(self):
        subpath = swift_string(CORE_SOURCES / "CLIInstallerService.swift", "helpersSubpath")
        for script in ("release.sh", "build.sh"):
            text = (REPO / "Scripts" / script).read_text()
            self.assertIn(subpath, text, script)
        cli_text = (REPO / "Scripts" / "build-cli.sh").read_text()
        # The CLI must be Apple-signed (silent Keychain sharing); ad-hoc is
        # a loud fallback, never the quiet default.
        self.assertIn("resolve-identity.sh", cli_text)
        self.assertIn("ad-hoc CLI will prompt", cli_text)
        self.assertIn("--options runtime", cli_text)

    def test_cli_package_is_hand_owned(self):
        # Generated files belong to ios-app-manager; the CLI package must
        # never be marked generated (a regen would wipe hand-written code).
        text = (REPO / "Packages" / "RunnerControlCLI" / "Package.swift").read_text()
        self.assertNotIn("Generated by", text)


if __name__ == "__main__":
    unittest.main()
